let n1 = 125.26;
console.log(Math.round(n1))

console.log(Math.floor(1.5))
console.log(Math.ceil(1.5))
console.log(Math.pow(2,3))

console.log(Math.random(0,1)*2+1)    


function getRandom(min,max){
    return Math.floor(Math.random()*(max-min+1)+5)
}
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))
console.log(getRandom(1,10))